### ISSUE TITLE
Readme to be updated?

### ISSUE THREAD

**Issue by FJMentz** [TripleParity/docks#11]
Should we remove the instructions for deployment from the docks readme since we now have instructions in our 'docks-demo' repo as well as the images being pulled to Dockerhub?

**Comment by egeldenhuys** [comment]
`docker build -f Dockerfile-prod -t docks-production . ` Can be removed

`docker run -it -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock docks-production` can be updated to use the image from the registry

**Comment by FJMentz** [comment]
Will you mind changing this quickly? @egeldenhuys

**Comment by FJMentz** [comment]
@egeldenhuys I did open a branch for changing the readme.

**Comment by egeldenhuys** [comment]
You can create a pull request :tada:
