### ISSUE TITLE
Language/framework used for Backend API

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks#14]
Are we sticking with Node Express or is there something that will serve our needs better?

**Comment by devosray** [comment]
Everyone has their own language preferences. We need to consider what the pros and cons are. I would personally go for Golang or Python, but that is only based on personal preferences.

Compiax did mention that they are using Node.js extensively. I don't know how much we will be pulling from their knowledge base but it might be something to consider.

**Comment by egeldenhuys** [comment]
My bad experience comes from using electron, so using node with express should be okay for the docks API. Since we are using JavaScript for the frontend as well, it should be easy for the entire team to contribute without having to learn another language.

If the API is well defined, the backend can be replaced at any time with another framework.
