### ISSUE TITLE
Use Travis CI to build docker images

### ISSUE THREAD

**Issue by devosray** [TripleParity/docks#5]
The process of building our docker images should be automated by Travis.

**Comment by egeldenhuys** [comment]
Much better solution: Use Docker Hub to build the images, and Travis CI for testing the code.

I have already configured the `tripleparity` Docker Hub organisation to build images using the `Dockerfile` in the root project directory, across all branches.

**Comment by egeldenhuys** [comment]
Images are now build under the Docker Hub organisation [tripleparity](https://hub.docker.com/u/tripleparity/)
